// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYDue7uFw36eQcgzZ8P3BBBZt-1EfWyQ',
    appId: '1:382116774206:web:7ae4a93df248b84136ac6f',
    messagingSenderId: '382116774206',
    projectId: 'depi-grad-f8228',
    authDomain: 'depi-grad-f8228.firebaseapp.com',
    storageBucket: 'depi-grad-f8228.firebasestorage.app',
    measurementId: 'G-SBCS56LDXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDChcIMN-Pl4i3IMvi5gAYLpZFkW4H8eMA',
    appId: '1:382116774206:android:6258bf0a2e278f4536ac6f',
    messagingSenderId: '382116774206',
    projectId: 'depi-grad-f8228',
    storageBucket: 'depi-grad-f8228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcu9iN9rnLWnVrir28mpy8ael2a9KehB4',
    appId: '1:382116774206:ios:e4876261af81c8b336ac6f',
    messagingSenderId: '382116774206',
    projectId: 'depi-grad-f8228',
    storageBucket: 'depi-grad-f8228.firebasestorage.app',
    iosBundleId: 'com.example.massar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcu9iN9rnLWnVrir28mpy8ael2a9KehB4',
    appId: '1:382116774206:ios:e4876261af81c8b336ac6f',
    messagingSenderId: '382116774206',
    projectId: 'depi-grad-f8228',
    storageBucket: 'depi-grad-f8228.firebasestorage.app',
    iosBundleId: 'com.example.massar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYYDue7uFw36eQcgzZ8P3BBBZt-1EfWyQ',
    appId: '1:382116774206:web:693db0409e8f87ea36ac6f',
    messagingSenderId: '382116774206',
    projectId: 'depi-grad-f8228',
    authDomain: 'depi-grad-f8228.firebaseapp.com',
    storageBucket: 'depi-grad-f8228.firebasestorage.app',
    measurementId: 'G-L8BK5R1WMG',
  );
}
